document.addEventListener('DOMContentLoaded', () => {
    getImage();
});

async function getImage() {
    const images = [
        "AkureyriIS",
        "AlbuquerqueUS",
        "AlessandriaIT",
        "AnchorageUS",
        "AtikokanCA",
        "AtlantaUS",
        "AucklandNZ",
        "BanffCA",
        "BangkokTH",
        "Belize CityBZ",
        "BergenNO",
        "BernCH",
        "BerlinDE",
        "BogotaCO",
        "BostonUS",
        "BudapestHU",
        "CalgaryCA",
        "CharlestonUS",
        "CharlotteUS",
        "ChicagoUS",
        "ChilliwackCA",
        "CincinnatiUS",
        "ColumbusUS",
        "CopenhagenDK",
        "DallasUS",
        "DaugavpilsLV",
        "DetroitUS",
        "DenverUS",
        "DohaQA",
        "DrumhellerCA",
        "DublinIE",
        "EdmontonCA",
        "EspooFI",
        "FairbanksUS",
        "GenevaCH",
        "GenoaIT",
        "GothenburgSE",
        "Grand MaraisUS",
        "HamiltonCA",
        "HartfordUS",
        "HelsinkiFI",
        "HoughtonUS",
        "IndianapolisUS",
        "JacksonvilleUS",
        "KamloopsCA",
        "Kansas CityUS",
        "KelownaCA",
        "KenoraCA",
        "LagosNG",
        "LaonFR",
        "Las VegasUS",
        "LondonCA",
        "LondonGB",
        "LyonFR",
        "ManaguaNI",
        "MelbourneAU",
        "Mexico CityMX",
        "MekkeliFI",
        "MilanIT",
        "MilwaukeeUS",
        "MinneapolisUS",
        "MontrealCA",
        "MumbaiCA",
        "New YorkUS",
        "Oklahoma CityUS",
        "OsloNO",
        "OuluFI",
        "Panama CityPA",
        "ParisFR",
        "PhiladelphiaUS",
        "PittsburghUS",
        "PortlandUS",
        "Prince GeorgeCA",
        "Puebla CityMX",
        "QuébecCA",
        "QuetzaltenangoGT",
        "ReginaCA",
        "ReykjavikIS",
        "RichmondUS",
        "RigaLV",
        "Rio de JaneiroBR",
        "RomeIT",
        "San FranciscoUS",
        "San JoséCR",
        "San Pedro HulaHN",
        "San SalvadorSV",
        "SantiagoCL",
        "São PauloBR",
        "SaskatoonCA",
        "SeattleUS",
        "SelfossIS",
        "Silver BayUS",
        "St LouisUS",
        "StockholmSE",
        "SuperiorUS",
        "Swift CurrentCA",
        "SydneyAU",
        "TallinnEE",
        "TegucigalpaHN",
        "Terrace BayCA",
        "Thunder BayCA",
        "TaipeiTW",
        "TikalGT",
        "TokyoJP",
        "TolucaMX",
        "TorontoCA",
        "ToulouseFR",
        "TurkuFI",
        "Two HarborsUS",
        "UppsalaSE",
        "VancouverCA",
        "ViennaAT",
        "VikIS",
        "WellingtonNZ",
        "WinnipegCA",
        "WuhanCN",
        "YellowknifeCA"
    ];

    const imageID = images[Math.floor(Math.random() * images.length)];
    document.body.style.backgroundImage = `url('images/${imageID}.jpeg')`;
}
