document.addEventListener('DOMContentLoaded', () => {
    getImage();
});

async function getImage() {
    const images = [
        "AkureyriIS",
        "AlbuquerqueUS",
        "AlessandriaIT",
        "AnchorageUS",
        "AtikokanCA",
        "AtlantaUS",
        "AucklandNZ",
        "BanffCA",
        "BangkokTH",
        "Belize CityBZ",
        "BergenNO",
        "BernCH",
        "BerlinDE",
        "BogotaCO",
        "BostonUS",
        "BrusselsBE",
        "BudapestHU",
        "CalgaryCA",
        "CharlestonUS",
        "CharlotteUS",
        "ChicagoUS",
        "ChilliwackCA",
        "CincinnatiUS",
        "ColumbusUS",
        "CopenhagenDK",
        "DallasUS",
        "DaugavpilsLV",
        "DetroitUS",
        "DenverUS",
        "DohaQA",
        "DrumhellerCA",
        "DubaiAE",
        "DublinIE",
        "EdmontonCA",
        "Elliot LakeCA",
        "EspooFI",
        "FairbanksUS",
        "Frankfurt am MainDE",
        "GatineauCA",
        "GhentBE",
        "GenevaCH",
        "GenoaIT",
        "GothenburgSE",
        "Grand MaraisUS",
        "HanoverDE",
        "HamiltonCA",
        "HartfordUS",
        "HaarlemNL",
        "HavanaCU",
        "HelsinkiFI",
        "HoughtonUS",
        "IndianapolisUS",
        "InnsbruckAT",
        "JacksonvilleUS",
        "KamloopsCA",
        "Kansas CityUS",
        "KelownaCA",
        "KenoraCA",
        "KotkaFI",
        "LagosNG",
        "LaonFR",
        "Las VegasUS",
        "LausanneCH",
        "LieksaFI",
        "LondonCA",
        "LondonGB",
        "LyonFR",
        "MadridES",
        "ManaguaNI",
        "MelbourneAU",
        "Mexico CityMX",
        "MikkeliFI",
        "MilanIT",
        "MilwaukeeUS",
        "MinneapolisUS",
        "MontrealCA",
        "MonterreyMX",
        "MumbaiIN",
        "NaplesIT",
        "New YorkUS",
        "NijmegenNL",
        "NorfolkGB",
        "Oklahoma CityUS",
        "OsloNO",
        "OuluFI",
        "Panama CityPA",
        "ParisFR",
        "PhiladelphiaUS",
        "PittsburghUS",
        "PocatelloUS",
        "PortlandUS",
        "Prince GeorgeCA",
        "Puebla CityMX",
        "QuébecCA",
        "QuetzaltenangoGT",
        "ReginaCA",
        "ReykjavikIS",
        "RichmondUS",
        "RigaLV",
        "Rio de JaneiroBR",
        "RomeIT",
        "San FranciscoUS",
        "San JoséCR",
        "San Pedro SulaHN",
        "San SalvadorSV",
        "SantiagoCL",
        "São PauloBR",
        "SaskatoonCA",
        "SeattleUS",
        "SelfossIS",
        "Silver BayUS",
        "St LouisUS",
        "StockholmSE",
        "SuperiorUS",
        "Swift CurrentCA",
        "SydneyAU",
        "TallinnEE",
        "TartuEE",
        "TampaUS",
        "TegucigalpaHN",
        "TaipeiTW",
        "TikalGT",
        "TokyoJP",
        "TolucaMX",
        "TorontoCA",
        "ToulouseFR",
        "TurkuFI",
        "TurinIT",
        "Two HarborsUS",
        "UppsalaSE",
        "VancouverCA",
        "ViennaAT",
        "VikIS",
        "WarsawPL",
        "WellingtonNZ",
        "WinnipegCA",
        "WuhanCN",
        "YellowknifeCA"
    ];

    const imageID = images[Math.floor(Math.random() * images.length)];
    document.body.style.backgroundImage = `url('images/${imageID}.jpeg')`;
}
